**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/data-types-and-missing-values).**

---

# Introduction

Run the following cell to load your data and some utility functions.

In [1]:
import pandas as pd

reviews = pd.read_csv("winemag-data-130k-v2.csv", index_col=0)

print("Setup complete.")

Setup complete.

# Exercises

## 1. 
Tipo de datos por columna

In [3]:
# Tipo de dato por columnas 
dtype = reviews.points.dtype

## 2. 
Cambiar tipo de datos de una columna especifica

In [6]:
## cambiar tipo de datos 
point_strings = reviews.points.astype(str)

## 3.
Saber Cuantos Nulos Hay

In [12]:
len(reviews[reviews.price.isnull()])

8996

In [10]:
reviews.price.isnull().sum()

8996

## 4. 
Reemplazar los valores nulos, contarlos por region_1, ordenarlos en forma descendiente

In [24]:
reviews.region_1.fillna("Unknown").value_counts().sort_values(ascending=False)

Unknown                 21247
Napa Valley              4480
Columbia Valley (WA)     4124
Russian River Valley     3091
California               2629
                        ...
Offida Rosso                1
Corton Perri√®res            1
Isle St. George             1
Geelong                     1
Paestum                     1
Name: region_1, Length: 1230, dtype: int64

# Keep going

Move on to **[renaming and combining](https://www.kaggle.com/residentmario/renaming-and-combining)**.

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/pandas/discussion) to chat with other learners.*